not running as sudo

diff --git a/setup-computer b/setup-computer
--- a/setup-computer
+++ b/setup-computer
@@ -1,66 +1,22 @@
 #!/bin/bash
 
-set -e #script stops executing if any command returns a non-zero code
-echo
-echo "Starting to setup computer..."
-echo "You must be a sudoer to run this script. Prove it."
-sudo echo "sudo SUCCESS." #challenge sudo
+# Perform tests to determine which OS this script is running in
+which pacman > /dev/null 2> /dev/null
+TEST_ARCH=$?
+which apt-get > /dev/null 2> /dev/null
+TEST_DEBIAN=$?
 
-#
-# Run all necessary apt-gets
-#
-echo
-echo "Installing software..."
-sudo apt-get update
-sudo apt-get install $(< resources/install_list.txt)
-echo 
-
-#
-# Install anything additional
-#
-echo
-echo "Installing additional things..."
-sudo ma-prepare
-echo
-
-#
-# Copy necessary resources
-#
-echo
-echo "Installing resources..."
-echo -n -e "\tcopying vimrc to home - "
-cp resources/vimrc ~/.vimrc
-echo -n -e "\tcopying ssh keys to home - "
-cp -r resources/ssh ~/.ssh
-echo -n -e "\tcopying indent.pro to home - "
-cp resources/indent.pro ~/.indent.pro
-echo -n -e "\tcopying bashrc to home - "
-cp resources/bashrc ~/.bashrc
-echo -n -e "\tcopying bash_aliases to home - "
-cp resources/bash_aliases ~/.bash_aliases
-echo "SUCCESS"
-echo
-
-#
-# Delete dumb resources
-#
-echo
-echo "Deleteing dumb resources..."
-echo -n -e "\tvarious dirs in home - "
-rm -rf ~/Pictures ~/Videos ~/Documents ~/Music ~/Public ~/Templates
-echo "SUCCESS"
-echo
-
-#
-# Configure git
-#
-echo
-echo -n "Configuring git..."
-git config --global user.name "Jordan Place"
-git config --global user.email "tapman90@gmail.com"
-git config --global credential.helper cache
-echo "SUCCESS"
-echo
-
-
-exit 0
+# Run the appropriate script
+if [ $TEST_ARCH -eq 0 ]; then
+	echo "You are running Arch Linux."
+	echo "Running ./setup-arch..."
+	./setup-arch	
+elif [ $TEST_DEBIAB -eq 0 ]; then
+	echo "You are running Debian Linux."
+	echo "Running ./setup-debian..."
+	./setup-debian
+else
+	echo "ERROR: Script cannot identify which OS you are running."
+	echo "Please fix this script and run it again."
+	exit 1
+fi
